import Painting from "./Painting";
import ShortBiography from "./ShortBiography";
import "./Styles/Biography.css"
function Biography() {
    return (
        <div className="Biography">
            <h1>Leonardo da Vinci</h1>
            <h2>Italian artist, engineer, and scientist</h2>
            <div className="flex">
                <div>
                    <p>Leonardo da Vinci, (Italian: “Leonardo from Vinci”) (born April 15, 1452, Anchiano, near Vinci, Republic of Florence [Italy]—died May 2, 1519, Cloux [now Clos-Lucé], France), Italian painter, draftsman, sculptor, architect, and engineer whose skill and intelligence, perhaps more than that of any other figure, epitomized the Renaissance humanist ideal. His Last Supper (1495–98) and Mona Lisa (c. 1503–19) are among the most widely popular and influential paintings of the Renaissance. His notebooks reveal a spirit of scientific inquiry and a mechanical inventiveness that were centuries ahead of their time.</p>
                    <p>The unique fame that Leonardo enjoyed in his lifetime and that, filtered by historical criticism, has remained undimmed to the present day rests largely on his unlimited desire for knowledge, which guided all his thinking and behaviour. An artist by disposition and endowment, he considered his eyes to be his main avenue to knowledge; to Leonardo, sight was man’s highest sense because it alone conveyed the facts of experience immediately, correctly, and with certainty. Hence, every phenomenon perceived became an object of knowledge, and saper vedere (“knowing how to see”) became the great theme of his studies. He applied his creativity to every realm in which graphic representation is used: he was a painter, sculptor, architect, and engineer. But he went even beyond that. He used his superb intellect, unusual powers of observation, and mastery of the art of drawing to study nature itself, a line of inquiry that allowed his dual pursuits of art and science to flourish.</p>
                </div>
                <ShortBiography/>
            </div>
            <h2>Life and works</h2>
            <h3>Early period: Florence</h3>
            <p>Leonardo’s parents were unmarried at the time of his birth. His father, Ser Piero, was a Florentine notary and landlord, and his mother, Caterina, was a young peasant woman who shortly thereafter married an artisan. Leonardo grew up on his father’s family’s estate, where he was treated as a “legitimate” son and received the usual elementary education of that day: reading, writing, and arithmetic. Leonardo did not seriously study Latin, the key language of traditional learning, until much later, when he acquired a working knowledge of it on his own. He also did not apply himself to higher mathematics—advanced geometry and arithmetic—until he was 30 years old, when he began to study it with diligent tenacity.</p>
            <p>Leonardo’s artistic inclinations must have appeared early. When he was about 15, his father, who enjoyed a high reputation in the Florence community, apprenticed him to artist Andrea del Verrocchio. In Verrocchio’s renowned workshop Leonardo received a multifaceted training that included painting and sculpture as well as the technical-mechanical arts. He also worked in the next-door workshop of artist Antonio Pollaiuolo. In 1472 Leonardo was accepted into the painters’ guild of Florence, but he remained in his teacher’s workshop for five more years, after which time he worked independently in Florence until 1481. There are a great many superb extant pen and pencil drawings from this period, including many technical sketches—for example, pumps, military weapons, mechanical apparatus—that offer evidence of Leonardo’s interest in and knowledge of technical matters even at the outset of his career.</p>
        
            <h3>First Milanese period (1482–99)</h3>
            <p>In 1482 Leonardo moved to Milan to work in the service of the city’s duke—a surprising step when one realizes that the 30-year-old artist had just received his first substantial commissions from his native city of Florence: the unfinished panel painting Adoration of the Magi for the monastery of San Donato a Scopeto and an altar painting for the St. Bernard Chapel in the Palazzo della Signoria, which was never begun. That he gave up both projects seems to indicate that he had deeper reasons for leaving Florence. It may have been that the rather sophisticated spirit of Neoplatonism prevailing in the Florence of the Medici went against the grain of Leonardo’s experience-oriented mind and that the more strict, academic atmosphere of Milan attracted him. Moreover, he was no doubt enticed by Duke Ludovico Sforza’s brilliant court and the meaningful projects awaiting him there.</p>
            <div className="flex">
                <p>Leonardo spent 17 years in Milan, until Ludovico’s fall from power in 1499. He was listed in the register of the royal household as pictor et ingeniarius ducalis (“painter and engineer of the duke”). Leonardo’s gracious but reserved personality and elegant bearing were well-received in court circles. Highly esteemed, he was constantly kept busy as a painter and sculptor and as a designer of court festivals. He was also frequently consulted as a technical adviser in the fields of architecture, fortifications, and military matters, and he served as a hydraulic and mechanical engineer. As he would throughout his life, Leonardo set boundless goals for himself; if one traces the outlines of his work for this period, or for his life as a whole, one is tempted to call it a grandiose “unfinished symphony.”</p>
                <Painting imgSource="https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Lady_with_an_Ermine_-_Leonardo_da_Vinci_%28adjusted_levels%29.jpg/1200px-Lady_with_an_Ermine_-_Leonardo_da_Vinci_%28adjusted_levels%29.jpg"
                          name="Leonardo da Vinci: Lady with an Ermine"
                          year="1489–91"/>
            </div>
            <p>As a painter, Leonardo completed six works in the 17 years in Milan. (According to contemporary sources, Leonardo was commissioned to create three more pictures, but these works have since disappeared or were never done.) From about 1483 to 1486, he worked on the altar painting The Virgin of the Rocks, a project that led to 10 years of litigation between the Confraternity of the Immaculate Conception, which commissioned it, and Leonardo; for uncertain purposes, this legal dispute led Leonardo to create another version of the work in about 1508. During this first Milanese period he also made one of his most famous works, the monumental wall painting Last Supper (1495–98) in the refectory of the monastery of Santa Maria delle Grazie (for more analysis of this work, see below Last Supper). Also of note is the decorative ceiling painting (1498) he made for the Sala delle Asse in the Milan Castello Sforzesco.</p>
            <p>During this period Leonardo worked on a grandiose sculptural project that seems to have been the real reason he was invited to Milan: a monumental equestrian statue in bronze to be erected in honour of Francesco Sforza, the founder of the Sforza dynasty. Leonardo devoted 12 years—with interruptions—to this task. In 1493 the clay model of the horse was put on public display on the occasion of the marriage of Emperor Maximilian to Bianca Maria Sforza, and preparations were made to cast the colossal figure, which was to be 16 feet (5 metres) high. But, because of the imminent danger of war, the metal, ready to be poured, was used to make cannons instead, causing the project to come to a halt. Ludovico’s fall in 1499 sealed the fate of this abortive undertaking, which was perhaps the grandest concept of a monument in the 15th century. The ensuing war left the clay model a heap of ruins.</p>
            <p>As a master artist, Leonardo maintained an extensive workshop in Milan, employing apprentices and students. Among Leonardo’s pupils at this time were Giovanni Antonio Boltraffio, Ambrogio de Predis, Bernardino de’ Conti, Francesco Napoletano, Andrea Solari, Marco d’Oggiono, and Salai. The role of most of these associates is unclear, leading to the question of Leonardo’s so-called apocryphal works, on which the master collaborated with his assistants. Scholars have been unable to agree in their attributions of these works.</p>
        
            <h3>Second Florentine period (1500–08) of Leonardo da Vinci</h3>
            <p>In December 1499 or, at the latest, January 1500—shortly after the victorious entry of the French into Milan—Leonardo left that city in the company of mathematician Lucas Pacioli. After visiting Mantua in February 1500, in March he proceeded to Venice, where the Signoria (governing council) sought his advice on how to ward off a threatened Turkish incursion in Friuli. Leonardo recommended that they prepare to flood the menaced region. From Venice he returned to Florence, where, after a long absence, he was received with acclaim and honoured as a renowned native son. In that same year he was appointed an architectural expert on a committee investigating damages to the foundation and structure of the church of San Francesco al Monte. A guest of the Servite order in the cloister of Santissima Annunziata, Leonardo seems to have been concentrating more on mathematical studies than painting, or so Isabella d’Este, who sought in vain to obtain a painting done by him, was informed by Fra Pietro Nuvolaria, her representative in Florence.</p>
            <p>Perhaps because of his omnivorous appetite for life, Leonardo left Florence in the summer of 1502 to enter the service of Cesare Borgia as “senior military architect and general engineer.” Borgia, the notorious son of Pope Alexander VI, had, as commander in chief of the papal army, sought with unexampled ruthlessness to gain control of the Papal States of Romagna and the Marches. When he enlisted the services of Leonardo, he was at the peak of his power and, at age 27, was undoubtedly the most compelling and most feared person of his time. Leonardo, twice his age, must have been fascinated by his personality. For 10 months Leonardo traveled across the condottiere’s territories and surveyed them. In the course of his activity, he sketched some of the city plans and topographical maps, creating early examples of aspects of modern cartography. At the court of Cesare Borgia, Leonardo also met Niccolò Machiavelli, who was temporarily stationed there as a political observer for the city of Florence.</p>
            <p>In the spring of 1503 Leonardo returned to Florence to make an expert survey of a project that attempted to divert the Arno River behind Pisa so that the city, then under siege by the Florentines, would be deprived of access to the sea. The plan proved unworkable, but Leonardo’s activity led him to consider a plan, first advanced in the 13th century, to build a large canal that would bypass the unnavigable stretch of the Arno and connect Florence by water with the sea. Leonardo developed his ideas in a series of studies; using his own panoramic views of the riverbank, which can be seen as landscape sketches of great artistic charm, and using exact measurements of the terrain, he produced a map in which the route of the canal (with its transit through the mountain pass of Serravalle) was shown. The project, considered time and again in subsequent centuries, was never carried out, but centuries later the express highway from Florence to the sea was built over the exact route Leonardo chose for his canal.</p>

            <h3>Second Milanese period (1508–13)</h3>
            <p>In May 1506 Charles d’Amboise, the French governor in Milan, asked the Signoria in Florence if Leonardo could travel to Milan. The Signoria let Leonardo go, and the monumental Battle of Anghiari remained unfinished. Unsuccessful technical experiments with paints seem to have impelled Leonardo to stop working on the mural; one cannot otherwise explain his abandonment of this great work. In the winter of 1507–08 Leonardo went to Florence, where he helped the sculptor Giovanni Francesco Rustici execute his bronze statues for the Florence Baptistery, after which time he settled in Milan.</p>
            <p>Honoured and admired by his generous patrons in Milan, Charles d’Amboise and King Louis XII, Leonardo enjoyed his duties, which were limited largely to advice in architectural matters. Tangible evidence of such work exists in plans for a palace-villa for Charles, and it is believed that he made some sketches for an oratory for the church of Santa Maria alla Fontana, which Charles funded. Leonardo also looked into an old project revived by the French governor: the Adda River that would link Milan with Lake Como by water.</p>
            <p>Leonardo’s scientific activity flourished during this period. His studies in anatomy achieved a new dimension in his collaboration with Marcantonio della Torre, a famous anatomist from Pavia. Leonardo outlined a plan for an overall work that would include not only exact, detailed reproductions of the human body and its organs but would also include comparative anatomy and the whole field of physiology. He even planned to finish his anatomical manuscript in the winter of 1510–11. Beyond that, his manuscripts are replete with mathematical, optical, mechanical, geological, and botanical studies. These investigations became increasingly driven by a central idea: the conviction that force and motion as basic mechanical functions produce all outward forms in organic and inorganic nature and give them their shape. Furthermore, he believed that these functioning forces operate in accordance with orderly, harmonious laws.</p>

            <h3>Last years (1513–19) of Leonardo da Vinci</h3>
            <div className="flex">
                <p>In 1513 political events—the temporary expulsion of the French from Milan—caused the now 60-year-old Leonardo to move again. At the end of the year, he went to Rome, accompanied by his pupils Melzi and Salai as well as by two studio assistants, hoping to find employment there through his patron Giuliano de’ Medici, brother of the new pope, Leo X. Giuliano gave him a suite of rooms in his residence, the Belvedere, in the Vatican. He also gave Leonardo a considerable monthly stipend, but no large commissions followed. For three years Leonardo remained in Rome at a time of great artistic activity: Donato Bramante was building St. Peter’s, Raphael was painting the last rooms of the pope’s new apartments, Michelangelo was struggling to complete the tomb of Pope Julius II, and many younger artists, such as Timoteo Viti and Sodoma, were also active. Drafts of embittered letters betray the disappointment of the aging master, who kept a low profile while he worked in his studio on mathematical studies and technical experiments or surveyed ancient monuments as he strolled through the city. Leonardo seems to have spent time with Bramante, but the latter died in 1514, and there is no record of Leonardo’s relations with any other artists in Rome. A magnificently executed map of the Pontine Marshes suggests that Leonardo was at least a consultant for a reclamation project that Giuliano de’ Medici ordered in 1514. He also made sketches for a spacious residence to be built in Florence for the Medici, who had returned to power there in 1512. However, the structure was never built.</p>
                <Painting imgSource="https://cdn.britannica.com/57/194757-050-FD0A1CAA/Portrait-Leonardo-da-Vinci.jpg"
                          name="Leonardo da Vinci: Portrait of Leonardo da Vinci."
                          year="1505-10"/>
            </div>
        </div>
    );
}

export default Biography;